### ISSUE TITLE
example 02-redux cause error message when updating reducer 

### ISSUE THREAD

**Issue by oriSomething** [milankinen/livereactload#64] opened 2015-10-07 08:07 UTC
```
<Provider> does not support changing `store` on the fly.
It is most likely that you see this error because you updated
to Redux 2.x and React Redux 2.x which no longer hot
reload reducers automatically.
See https://github.com/rackt/react-redux/releases/tag/v2.0.0
for the migration instructions.
```

**Comment by milankinen** [comment] 2015-10-12 11:04
This is an issue/feature in `redux`. As you can see, the warning doesn't affect live reloading.

**Comment by milankinen** [comment] 2015-10-18 11:23
Version `2.0.4` introduces a way to accept the reloaded module, thus preventing this error.

Please see https://github.com/milankinen/livereactload/blob/master/examples/02-redux/store/configureStore.js

**Comment by c089** [comment] 2016-02-04 12:19
@milankinen: I'm still seeing this warning with `2.1.1` despite the `return true` in my `configureStore`:

```
export default function configureStore(initialState) {
  const devTools = window.devToolsExtension ? window.devToolsExtension() : undefined;
  const store = createStore(reducer, initialState, devTools);

  if (module.onReload) {
    module.onReload(() => {
      store.replaceReducer(require('./reducers').default);
      return true;
    });
  }

  return store;
}
```

**Comment by c089** [comment] 2016-02-04 13:57
Hm, running the example from the repo I don't get the error. I wonder if there's anything besides `configureStore` I could have misconfigured...

**Comment by milankinen** [comment] 2016-02-05 08:38
@c089, is your repo (having this problem) public so that I can check it out myself?

**Comment by c089** [comment] 2016-02-05 11:40
Unfortunately not as it's a client project. But I'll try to reproduce this with a new, minimal setup. The only thing I can think of right now is that it uses newer versions of the libraries than the 02 example...

**Comment by milankinen** [comment] 2016-02-05 11:50
@c089 what Redux version you're using in your client project at the moment (could you check the actual version from your `node_modules/redux/package.json`)?

**Comment by c089** [comment] 2016-02-05 12:02
```
❯ npm ls | ag redux
├─┬ react-redux@4.2.1
├─┬ redux@3.2.1
```

**Comment by milankinen** [comment] 2016-02-05 13:25
Hmmm strange... Tested with newer versions and got no problems:

```bash
02-redux (development *) $ npm i
npm WARN package.json livereactload-flux-with-redux-example@2.0.0 No repository field.
redux@3.2.1 node_modules/redux
├── loose-envify@1.1.0 (js-tokens@1.0.2)
└── lodash@4.2.1

react-redux@4.3.0 node_modules/react-redux
├── invariant@2.2.0
├── hoist-non-react-statics@1.0.5
├── loose-envify@1.1.0 (js-tokens@1.0.2)
└── lodash@4.2.1
```

**Comment by DjebbZ** [comment] 2016-02-09 10:37
Same problem here. The only difference in the hot-reloading code is that I don't use `.default` after requiring my reducer. I think it's because even if I use Babel 6, my module doesn't have a default export but several ones, and also that I use commonJS and not ES2015.

Versions used (`npm ls | grep redux`) :

```
├─┬ react-redux@4.1.2
├── redux@3.0.6
├── redux-logger@2.4.0
├── redux-thunk@1.0.3
```

**Comment by milankinen** [comment] 2016-02-09 10:41
Thanks! I'll test it with those versions.

Is it possible to identify which files with modifications cause the warning? `reducers.js` (or its dependencies)?  Or perhaps some other files?

**Comment by DjebbZ** [comment] 2016-02-09 10:43
The warning came from my `reducer` file. Editing everything else -- actions, app entry point, React components, other redux stuff like `mapStateToProps()` -- worked perfectly.

**Comment by sleepylemur** [comment] 2016-03-06 20:18
Getting this warning from a fresh clone of the example 02-redux. It appears as though module.onReload isn't being triggered.

**Comment by sassanh** [comment] 2016-07-06 03:19
I get the error in a fresh clone of the repository in 02-redux example too. Editing counter.js generates the warning.

**Comment by milankinen** [comment] 2016-07-06 07:26
Going to take a look at this during this week! Probably linked with #111 somehow.

**Comment by sassanh** [comment] 2016-07-10 10:40
@milankinen could you please give me some instructions how should I use livereactload to have hot module loading with react, redux and router? I really prefer browserify environment but if I can't have hot module loading for my project I'll be forced to use webpack. I guess I can manage it to work if you manage to make example 02-redux work though it'd be much more helpful if you could add router to it too.

**Comment by sassanh** [comment] 2016-07-12 09:50
@milankinen ok I was able to use livereactload with `redux` and `route`.
I described my problem with `route` in detail here: https://github.com/milankinen/livereactload/issues/43#issuecomment-231990841

My problem with `redux` was that I wasn't using `react-proxy@1.x` nor `babel-plugin-react-transform` so my components were not wrapped in proxies.
It'd be much easier to find the issue if livereactload raised an explicit error when user is not applying the required transform. The weird thing is livereactload was working without `livereactload/babel-transform` if I didn't use redux or route.

**Comment by milankinen** [comment] 2016-07-13 11:23
@sassanh Very good idea! It would be easy to implement as well. Creating another issue for that.

I'll keep this issue open because there is a bug in the current `2.2.4` release (see https://github.com/milankinen/livereactload/issues/43#issuecomment-232325463).

**Comment by milankinen** [comment] 2017-01-03 19:18
This should be fixed a long time ago. Closing this one and reopen if any issues still exist.

**Closed by milankinen** 2017-01-03 19:18 UTC
Labels: bug
